In [20]:
import pandas as pd
from get_path import get_path as gp

In [21]:
from sklearn.impute import KNNImputer, SimpleImputer

In [22]:
df = pd.read_csv(gp())
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,NaN,10.38,122.80,1001.0,0.1184,0.2776,0.3001,0.14710,0.2419,0.07871,...,17.33,NaN,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,NaN,NaN,0.0869,0.07017,NaN,0.05667,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,NaN,0
2,19.69,21.25,130.00,1203.0,0.1096,0.1599,NaN,NaN,NaN,0.05999,...,25.53,NaN,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.1425,0.2839,0.2414,NaN,0.2597,0.09744,...,26.50,NaN,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,NaN,NaN,NaN,0.1328,0.1980,NaN,0.1809,NaN,...,16.67,152.2,1575.0,0.1374,NaN,0.4000,0.1625,0.2364,0.07678,0

In [23]:
#create var x which is all rows but first three columns
x = df.iloc[:, 0:3]

x

     mean radius  mean texture  mean perimeter
0            NaN         10.38          122.80
1          20.57         17.77          132.90
2          19.69         21.25          130.00
3          11.42         20.38           77.58
4          20.29         14.34             NaN
..           ...           ...             ...
564        21.56         22.39          142.00
565          NaN         28.25          131.20
566        16.60         28.08          108.30
567        20.60         29.33          140.10
568         7.76           NaN           47.92

[569 rows x 3 columns]

# ***KNN-Imputer***

In [57]:
knn_cleaner = KNNImputer(n_neighbors = 5)

In [58]:
k_transform = knn_cleaner.fit_transform(x)

In [59]:
k_transform

array([[ 13.9636,  10.38  , 122.8   ],
       [ 20.57  ,  17.77  , 132.9   ],
       [ 19.69  ,  21.25  , 130.    ],
       ...,
       [ 16.6   ,  28.08  , 108.3   ],
       [ 20.6   ,  29.33  , 140.1   ],
       [  7.76  ,  20.014 ,  47.92  ]], shape=(569, 3))

# ***Difference between mean and KNN imputers***

In [65]:
mean_cleaner = SimpleImputer()

In [66]:
m_transform = mean_cleaner.fit_transform(x)

In [62]:
diff = ((k_transform - m_transform) / k_transform) * 100 #computing difference % between mean and knn

In [63]:
diff

array([[-0.68712737,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  3.50839778,  0.        ]], shape=(569, 3))

In [64]:
diff.mean() #very low diff for this case

np.float64(-0.364652538014595)

# ***KNN Imputer with weights***
#### `Distance between neighbours α 1 / Numerical Weight `

In [67]:
cleaner = KNNImputer(n_neighbors = 5, weights = "distance")

In [68]:
cleaner.fit_transform(x)

array([[ 14.88010103,  10.38      , 122.8       ],
       [ 20.57      ,  17.77      , 132.9       ],
       [ 19.69      ,  21.25      , 130.        ],
       ...,
       [ 16.6       ,  28.08      , 108.3       ],
       [ 20.6       ,  29.33      , 140.1       ],
       [  7.76      ,  24.62930137,  47.92      ]], shape=(569, 3))